### ISSUE TITLE
how to get uNet_test.npy??

### ISSUE THREAD

**Issue by Aries5522** [frostinassiky/gtad#18] opened 2020-06-26 11:01 UTC
thanks for sharing code!!
I have a questions in you rep.
Becaues I want to run on my own dataset,and in postprocess I met this problem??
Looking forword your reply,thanks

**Comment by frostinassiky** [comment] 2020-07-01 20:52
Hi @Aries5522 . Thanks for your interest in G-TAD. 

`uNet_test.npy` contains the classification results for each video in the test set. You can use **any** video classification model to produce the prediction.

**Comment by frostinassiky** [comment] 2020-07-01 20:53
Duplicate of #10

**Closed as completed** 2020-07-03 17:08 UTC

**Comment by Aries5522** [comment] 2020-07-10 11:07
Thanks for your reply。I will to train my own classification model to classified the proposal.
